version: "3.9"

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/front
      - /front/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
      - "5555:5555"
    command: sh -c "npm install && npm run dev && npx prisma studio --port 5555"
    stdin_open: true
    tty: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    tty: true
  db:
    image: postgres:14.2
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - ./front/.env
    ports:
      - "5432:5432"
